name: publish

on:
  push:
    branches:
    - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    container:
      image: gcr.io/linkerd-io/website-builder:1.3.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Publish
      run: echo "Publishing.."
